# Generated by Django 4.2.4 on 2023-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INOUT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings_godown_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_list', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='settings_payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='settings_purchase_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='settings_supplier_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='settings_uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=200)),
            ],
        ),
    ]
