# Generated by Django 4.2.4 on 2023-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INOUT', '0002_settings_godown_list_settings_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hsn_code', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('variant', models.CharField(max_length=200)),
                ('sub_variant', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('uom', models.CharField(max_length=200)),
                ('invoice_num', models.CharField(max_length=200)),
                ('supplier_name', models.CharField(max_length=200, null=True)),
                ('purchase_status', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('godown', models.CharField(max_length=200)),
                ('due', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('igst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('xtra1', models.CharField(default='na', max_length=200)),
                ('xtra2', models.CharField(default='na', max_length=200)),
            ],
        ),
    ]
